-- PaGamO 115 class authorization reporting
-- Run in Supabase SQL editor before publishing the site.

create table if not exists public.pagamo_submissions (
  id bigint generated by default as identity primary key,
  school_year integer not null default 115,
  city text not null default '桃園市',
  school_name text not null default '桃園市龍潭區石門國民小學'
    check (school_name in ('桃園市龍潭區石門國民小學', '桃園市石門國民小學')),
  school_code text not null default '034725'
    check (school_code = '034725'),
  teacher_name text not null,
  grade integer not null check (grade between 3 and 6),
  class_num integer not null check (class_num between 1 and 99),
  student_count integer not null check (student_count between 1 and 60),
  subject_chinese boolean not null default false,
  subject_english boolean not null default false,
  subject_math boolean not null default false,
  submitted_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pagamo_submissions_subject_check
    check (
      (case when subject_chinese then 1 else 0 end) +
      (case when subject_english then 1 else 0 end) +
      (case when subject_math then 1 else 0 end)
      between 1 and 2
    ),
  constraint pagamo_submissions_unique_class
    unique (school_code, grade, class_num)
);

create or replace function public.set_pagamo_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_pagamo_submissions_updated_at on public.pagamo_submissions;
create trigger trg_pagamo_submissions_updated_at
before update on public.pagamo_submissions
for each row
execute function public.set_pagamo_updated_at();

alter table public.pagamo_submissions enable row level security;

-- Public form can create and update class rows.
-- If this table already exists with the old school_name check, run this migration once:
-- alter table public.pagamo_submissions drop constraint if exists pagamo_submissions_school_name_check;
-- alter table public.pagamo_submissions add constraint pagamo_submissions_school_name_check
--   check (school_name in ('桃園市龍潭區石門國民小學', '桃園市石門國民小學'));

drop policy if exists "Allow public insert" on public.pagamo_submissions;
create policy "Allow public insert"
on public.pagamo_submissions
for insert
to anon
with check (true);

drop policy if exists "Allow public upsert update" on public.pagamo_submissions;
create policy "Allow public upsert update"
on public.pagamo_submissions
for update
to anon
using (true)
with check (true);

drop policy if exists "Allow public delete for admin page" on public.pagamo_submissions;
create policy "Allow public delete for admin page"
on public.pagamo_submissions
for delete
to anon
using (school_code = '034725');

-- Do not add a public SELECT policy for a production deployment.
-- The current static admin page can only read data if SELECT is opened to anon,
-- which is convenient for a trusted temporary site but exposes all submissions.
